In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

mapp = pd.read_excel('행정동코드_매핑정보_20200325 (2).xlsx')[1:]
mapp['행자부행정동코드'] = pd.to_numeric(mapp['행자부행정동코드'])
df = pd.read_csv('LOCAL_PEOPLE_DONG_202304.csv')
for i in range(5,10):
    dft = pd.read_csv('LOCAL_PEOPLE_DONG_20230%d.csv'% i)
    df = pd.concat([df,dft[1:]],ignore_index=True)
for i in range(10,13):
    dft = pd.read_csv('LOCAL_PEOPLE_DONG_2023%d.csv'% i)
    df = pd.concat([df,dft[1:]],ignore_index=True)
for i in range(1,4):
    dft = pd.read_csv('LOCAL_PEOPLE_DONG_20240%d.csv'% i)
    df = pd.concat([df,dft[1:]],ignore_index=True)
df.reset_index(inplace=True)
tpcolumns = df.columns[1:]
df.drop(columns='여자70세이상생활인구수', inplace = True)
df.columns = tpcolumns
df.to_csv('data.csv',encoding='cp949')

# 월별 데이터 파일(.csv) 합치는 코드
# data.csv 파일 생성 후에는 아래의 코드 사용 가능

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

mapp = pd.read_excel('행정동코드_매핑정보_20200325 (2).xlsx')[1:]
mapp['행자부행정동코드'] = pd.to_numeric(mapp['행자부행정동코드'])
df = pd.read_csv('data.csv', encoding='cp949')

# 행정동코드, 생활인구데이터 통합 파일 불러오기

In [2]:
dddd = mapp.loc[mapp['시군구명'] == '광진구']
df1 = pd.DataFrame()
for i in range(15):
    df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
    
# df1은 생활인구데이터에서 광진구 데이터만을 뽑은 데이터

C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])
C:\Users\User\AppData\Local\Temp\ipykernel_6988\849434152.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df1 = df1.append(df.loc[df['행정동코드'] == dddd.행자부행정동코드.tolist()[i]])

In [3]:
df1_groupby = df1.groupby('행정동코드')[['총생활인구수']].sum()
df2 = pd.read_excel('주민등록인구_20240401234727.xlsx')
# df1_groupby는 광진구 행정동별 총생활인구수를 나타낸 데이터
# df2는 광진구 동별 주민등록인구데이터 (2023년 4분기 기준)

In [ ]:
df_tp = pd.concat([df1_groupby.reset_index(),df2], axis = 1)
df_tp
# 광진구 동별 생활인구 데이터와 주민등록인구 데이터를 통합하여 데이터프레임화

In [4]:
dtime = df1.loc[df1['시간대구분'] < 7].append(df1.loc[df1['시간대구분'] > 21])
df3_groupby = dtime.groupby('행정동코드')[['총생활인구수']].sum()

# dtime은 df1에서 야간시간대(오후 22시부터 다음날 오전 6시까지) 데이터만을 뽑은 데이터 
# df3_groupby는 dtime에서 행정동별 총생활인구수를 뽑은 데이터 (거주인구)

C:\Users\User\AppData\Local\Temp\ipykernel_6988\1624052218.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dtime = df1.loc[df1['시간대구분'] < 7].append(df1.loc[df1['시간대구분'] > 21])

In [24]:
df_ha = pd.concat([df1_groupby, df3_groupby], axis = 1)
df_ha.columns = ['총생활인구수', '생활인구수_야간']

df_ha['주민등록인구'] = [27645,21465,15691,20882,16008,28006,11496,34210,22745,23949,27543,23405,23833,26230,28072] # df2.소계 이런식으로 하려했는데 자꾸 nan로 떠서 임시로...
df_ha['동'] = ['화양동','군자동','중곡1동','중곡2동','중곡3동','중곡4동','능동','광장동','자양1동','자양2동','자양3동','자양4동','구의1동','구의2동','구의3동']
df_ha['Code'] = [11050530,11050540,11050550,11050560,11050570,11050580,11050590,11050630,11050640,11050650,11050660,11050670,11050600,11050610,11050620]
df_ha

                총생활인구수      생활인구수_야간  주민등록인구     동      Code
행정동코드
11215710  3.674134e+08  1.327109e+08   27645   화양동  11050530
11215730  2.013533e+08  7.275452e+07   21465   군자동  11050540
11215740  1.330084e+08  5.244103e+07   15691  중곡1동  11050550
11215750  1.624126e+08  7.181793e+07   20882  중곡2동  11050560
11215760  1.302077e+08  5.198615e+07   16008  중곡3동  11050570
11215770  2.119339e+08  8.621066e+07   28006  중곡4동  11050580
11215780  1.328759e+08  4.070192e+07   11496    능동  11050590
11215810  3.073135e+08  1.197747e+08   34210   광장동  11050630
11215820  2.161818e+08  8.515635e+07   22745  자양1동  11050640
11215830  1.879048e+08  7.663255e+07   23949  자양2동  11050650
11215840  2.143469e+08  8.260667e+07   27543  자양3동  11050660
11215847  2.416191e+08  8.518223e+07   23405  자양4동  11050670
11215850  2.036843e+08  8.759782e+07   23833  구의1동  11050600
11215860  1.766318e+08  7.407233e+07   26230  구의2동  11050610
11215870  2.647962e+08  9.459041e+07   28072  구의3동  11050620

In [25]:
scaler = StandardScaler()
scaler.fit(df_ha[['총생활인구수','생활인구수_야간', '주민등록인구']])
df2_scaled = scaler.transform(df_ha[['총생활인구수','생활인구수_야간', '주민등록인구']])

df2_scaled_d = pd.DataFrame(data=df2_scaled, columns = ['총생활인구수','생활인구수_야간', '주민등록인구'])
df2_scaled_d.index = df_ha.index
df2_scaled_d['생활인구수_주간'] = df2_scaled_d.총생활인구수 - df2_scaled_d.생활인구수_야간
df2_scaled_d['생활인구수_주야차'] = df2_scaled_d.생활인구수_주간 - df2_scaled_d.생활인구수_야간
df2_scaled_d['주민등록인구-총생활인구'] = df2_scaled_d.주민등록인구 - df2_scaled_d.총생활인구수
df2_scaled_d[['동','Code']] = df_ha[['동','Code']]
df2_scaled_d

# 데이터의 스케일을 맞춰주기 위해 표준화 작업 시행 (StandardScaler)

,총생활인구수,생활인구수_야간,주민등록인구,생활인구수_주간,생활인구수_주야차,주민등록인구-총생활인구,동,Code
행정동코드,,,,,,,,
11215710,2.476125,2.245441,0.756321,0.230684,-2.014757,-1.719805,화양동,11050530
11215730,-0.137876,-0.355482,-0.347875,0.217605,0.573087,-0.209999,군자동,11050540
11215740,-1.213715,-1.236685,-1.379530,0.022970,1.259656,-0.165815,중곡1동,11050550
11215750,-0.750854,-0.396111,-0.452041,-0.354743,0.041368,0.298813,중곡2동,11050560
11215760,-1.257802,-1.256418,-1.322891,-0.001384,1.255034,-0.065088,중곡3동,11050570
11215770,0.028675,0.228249,0.820821,-0.199573,-0.427822,0.792146,중곡4동,11050580
11215780,-1.215801,-1.745931,-2.129061,0.530129,2.276060,-0.913260,능동,11050590
11215810,1.530075,1.684263,1.929305,-0.154188,-1.838451,0.399230,광장동,11050630
11215820,0.095544,0.182512,-0.119175,-0.086969,-0.269481,-0.214718,자양1동,11050640
11215830,-0.349574,-0.187252,0.095947,-0.162322,0.024930,0.445521,자양2동,11050650
11215840,0.066659,0.071907,0.738096,-0.005248,-0.077154,0.671437,자양3동,11050660
11215847,0.495959,0.183635,-0.001251,0.312324,0.128689,-0.497210,자양4동,11050670
11215850,-0.101185,0.288424,0.075221,-0.389608,-0.678032,0.176406,구의1동,11050600
11215860,-0.527026,-0.298315,0.503499,-0.228711,0.069604,1.030525,구의2동,11050610
11215870,0.860796,0.591764,0.832614,0.269033,-0.322731,-0.028183,구의3동,11050620

In [26]:
df2_scaled_d.corr()

# 상관관계 분석 (Code는 무의미)

C:\Users\User\AppData\Local\Temp\ipykernel_6988\4052203524.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df2_scaled_d.corr()

,총생활인구수,생활인구수_야간,주민등록인구,생활인구수_주간,생활인구수_주야차,주민등록인구-총생활인구,Code
총생활인구수,1.000000,0.967348,0.773990,0.127772,-0.879053,-0.336162,0.089326
생활인구수_야간,0.967348,1.000000,0.860032,-0.127772,-0.971176,-0.159620,0.103230
주민등록인구,0.773990,0.860032,1.000000,-0.336700,-0.889753,0.336162,0.344627
생활인구수_주간,0.127772,-0.127772,-0.336700,1.000000,0.360498,-0.690846,-0.054407
생활인구수_주야차,-0.879053,-0.971176,-0.889753,0.360498,1.000000,-0.015915,-0.110160
주민등록인구-총생활인구,-0.336162,-0.159620,0.336162,-0.690846,-0.015915,1.000000,0.379729
Code,0.089326,0.103230,0.344627,-0.054407,-0.110160,0.379729,1.000000